//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayman_restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchasing
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_category { get; set; }
        public Nullable<int> p_price { get; set; }
        public string p_quantity { get; set; }
        public string p_namesupplier { get; set; }
        public Nullable<int> p_idbill { get; set; }
    }
}
