//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayman_restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int s_id { get; set; }
        public string s_name { get; set; }
        public string s_address { get; set; }
        public Nullable<int> s_phon { get; set; }
        public string s_fex { get; set; }
        public string s_name_company { get; set; }
    }
}
