//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayman_restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbill
    {
        public int id { get; set; }
        public string item_name { get; set; }
        public Nullable<int> units { get; set; }
        public Nullable<double> unit_total { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> net { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<double> unit_pric { get; set; }
    }
}
