//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayman_restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_pass { get; set; }
        public string u_user { get; set; }
        public string u_supplier { get; set; }
        public string purchasing { get; set; }
        public string bill { get; set; }
        public string product { get; set; }
    }
}
